name: Tweet Job
"on":
  push:
    branches:
      - test-run
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_tweet_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: node app
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          BOT_ID: ${{ secrets.BOT_ID }}
          DEFAULT_ICON: ${{ secrets.DEFAULT_ICON }}
